Update INSTALL script with sanity checks and an option to specify which ruby to use.

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -1,11 +1,56 @@
 #!/bin/sh
 
+# Abort if any command returns an error
+set -e
+
 # Script to install required external packages
 
 # Set location of ruby to use
-#RUBY=/whome/harrop/opt/ruby/bin/ruby
-RUBY=/whome/harrop/opt/ruby-1.8.7-p352/bin/ruby
-#RUBY=ruby
+RUBY=`which ruby`
+for arg in $@; do
+  case $arg in
+    --with-ruby=*) RUBY=`echo $arg | cut -f 2 -d "="`/bin/ruby;;
+    -h|--help) echo
+               echo "Run this script to install the Workflow Manager"
+               echo
+               echo "INSTALL [--with-ruby=/path/to/ruby]"
+               echo
+               exit;;
+    *)
+  esac 
+done
+
+# Make sure ruby exists
+if [ -x $RUBY ]; then
+  echo "Installing using $RUBY"
+else
+  echo "Installation failed.  $RUBY does not exist"
+  exit 1
+fi
+
+# Make sure ruby is at least 1.8.7 or higher
+good_ruby=`$RUBY -e "puts RUBY_VERSION >= '1.8.7'"`
+if [ "$good_ruby" == "false" ]; then
+  echo "Ruby 1.8.7 or higher is required"
+  exit 1
+fi
+
+# Replace ruby shebangs with path to ruby
+for file in `ls sbin`; do
+
+  # Skip files that are links
+  if [ -L sbin/$file ]; then
+    continue
+  fi
+
+  # Replace first line with correct shebang
+  sed "1c\#!${RUBY}" sbin/$file > sbin/$file.new
+  mv sbin/$file.new sbin/$file
+
+  # Make sure the new file is executable
+  chmod ugo+x sbin/$file
+
+done
 
 # Package versions
 LIBXML_VERSION="2.3.3"
